#!/usr/bin/env python3
"""Generate Morandi-style color palette from Noctalia's Material You colors and apply to system."""

import json
import colorsys
import os
import re
import sys
import subprocess
import argparse
from pathlib import Path

NOCTALIA_COLORS = Path.home() / ".config/noctalia/colors.json"
NIRI_COLORS_KDL = Path.home() / ".config/niri/cfg/colors.kdl"
MANGO_CONFIG = Path.home() / ".config/mango/config.conf"
STARSHIP_TOML = Path.home() / ".config/starship.toml"
FCITX5_THEME = Path.home() / ".local/share/fcitx5/themes/morandi/theme.conf"
FASTFETCH_CONFIG = Path.home() / ".config/fastfetch/config.jsonc"
ALACRITTY_TOML = Path.home() / ".config/alacritty/alacritty.toml"
KDE_OUTPUT = Path.home() / ".local/share/color-schemes/Morandi-dark.colors"

def hex_to_hsl(hex_color):
    r = int(hex_color[1:3], 16) / 255
    g = int(hex_color[3:5], 16) / 255
    b = int(hex_color[5:7], 16) / 255
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    return h * 360, s * 100, l * 100

def hsl_to_hex(h, s, l):
    h = h % 360
    s = max(0, min(100, s)) / 100
    l = max(0, min(100, l)) / 100
    r, g, b = colorsys.hls_to_rgb(h / 360, l, s)
    return f"#{int(r*255):02x}{int(g*255):02x}{int(b*255):02x}"

def morandi(hex_color, sat_reduction=0.3, light_adjust=0, warm_shift=0, sat_cap=45):
    h, s, l = hex_to_hsl(hex_color)
    s = s * (1 - sat_reduction)
    h = (h + warm_shift) % 360
    l = max(0, min(100, l + light_adjust))
    s = min(s, sat_cap)
    return hsl_to_hex(h, s, l)

def blend(c1, c2, ratio=0.5):
    r1, g1, b1 = int(c1[1:3], 16), int(c1[3:5], 16), int(c1[5:7], 16)
    r2, g2, b2 = int(c2[1:3], 16), int(c2[3:5], 16), int(c2[5:7], 16)
    r = int(r1 + (r2 - r1) * ratio)
    g = int(g1 + (g2 - g1) * ratio)
    b = int(b1 + (b2 - b1) * ratio)
    return f"#{r:02x}{g:02x}{b:02x}"

def generate_palette(c):
    p = {}
    primary = c.get("mPrimary", c.get("primary"))
    secondary = c.get("mSecondary", c.get("secondary"))
    tertiary = c.get("mTertiary", c.get("tertiary"))
    error = c.get("mError", c.get("error"))
    surface = c.get("mSurface", c.get("surface"))
    on_surface = c.get("mOnSurface", c.get("on_surface"))
    surface_var = c.get("mSurfaceVariant", c.get("surface_variant"))
    outline = c.get("mOutline", c.get("outline"))

    p["base"] = morandi(surface, 0.5, -2)
    p["mantle"] = morandi(surface, 0.6, -5)
    p["surface0"] = morandi(surface_var, 0.4, 2)
    p["surface1"] = morandi(surface_var, 0.3, 5)
    p["surface2"] = morandi(surface_var, 0.2, 8)
    p["overlay0"] = morandi(outline, 0.3, -2)
    p["overlay1"] = morandi(outline, 0.2, 2)
    p["overlay2"] = morandi(outline, 0.1, 5)
    p["subtext0"] = morandi(on_surface, 0.4, -8)
    p["subtext1"] = morandi(on_surface, 0.3, -4)
    p["text"] = morandi(on_surface, 0.2, 0)
    p["love"] = morandi(error, 0.25, -15)
    p["rose"] = morandi(blend(primary, error, 0.6), 0.3, -15, 5)
    p["gold"] = morandi(blend(primary, "#d4a574", 0.3), 0.35, -10, 15)
    p["peach"] = morandi(blend(error, "#d4a574", 0.4), 0.3, -10, 10)
    p["pine"] = morandi(tertiary, 0.3, -18, -5)
    p["foam"] = morandi(secondary, 0.35, -18, -5)
    p["iris"] = morandi(primary, 0.25, -18)
    p["sky"] = morandi(tertiary, 0.35, -18, -10)

    h, s, l = hex_to_hsl(p["surface1"])
    p["fcitx5_bg"] = hsl_to_hex(h, s * 0.6, min(l, 20))
    p["fcitx5_bg_alt"] = hsl_to_hex(h, s * 0.5, min(l + 3, 22))
    ih, is_, il = hex_to_hsl(p["iris"])
    p["fcitx5_hl_bg"] = hsl_to_hex(ih, is_, min(il, 38))
    p["fcitx5_text"] = p["text"]
    p["fcitx5_hl_text"] = p["base"]
    return p

def write_niri(palette):
    kdl = f"""// Auto-generated by morandi-gen.py — do not edit manually
layout {{
    focus-ring {{
        width 3
        active-gradient from="{palette['iris']}" to="{palette['pine']}" angle=45 relative-to="workspace-view"
        inactive-gradient from="{palette['surface0']}" to="{palette['surface1']}" angle=45 relative-to="workspace-view"
    }}
    border {{
        off
    }}
    shadow {{
        color "{palette['surface0']}70"
    }}
    tab-indicator {{
        active-color "{palette['iris']}"
        inactive-color "{palette['surface1']}"
        urgent-color "{palette['love']}"
    }}
    insert-hint {{
        color "{palette['iris']}80"
    }}
}}
recent-windows {{
    highlight {{
        active-color "{palette['iris']}"
        urgent-color "{palette['love']}"
    }}
}}
"""
    with open(NIRI_COLORS_KDL, "w") as f:
        f.write(kdl)

def write_mango(palette):
    if not MANGO_CONFIG.exists(): return
    content = MANGO_CONFIG.read_text()
    
    def c(hex_val, alpha="ff"):
        return "0x" + hex_val.lstrip("#").lower() + alpha
        
    replacements = {
        "focuscolor": c(palette["iris"]),
        "bordercolor": c(palette["surface1"]),
        "shadowscolor": c(palette["surface0"], "70"),
        "rootcolor": c(palette["base"]),
        "urgentcolor": c(palette["love"]),
        "overlaycolor": c(palette["iris"]),
        "scratchpadcolor": c(palette["foam"]),
    }
    
    for key, val in replacements.items():
        content = re.sub(fr"^{key}\s*=.*", f"{key}={val}", content, flags=re.MULTILINE)
        
    MANGO_CONFIG.write_text(content)

def write_starship(palette):
    if not STARSHIP_TOML.exists(): return
    with open(STARSHIP_TOML, "r") as f:
        content = f.read()
    keys = ["base", "mantle", "surface0", "surface1", "surface2", "overlay0", "overlay1", "overlay2", "subtext0", "subtext1", "text", "love", "gold", "peach", "rose", "pine", "foam", "iris", "sky"]
    new_palette = "[palettes.custom]\n" + "\n".join(f"{k} = '{palette[k]}'" for k in keys) + "\n"
    content, count = re.subn(r"\[palettes\.custom\][\s\S]*?(?=\n\[|\Z)", new_palette, content)
    if count == 0: content += "\n" + new_palette
    with open(STARSHIP_TOML, "w") as f:
        f.write(content)

def write_fcitx5(palette):
    theme_dir = FCITX5_THEME.parent
    theme_dir.mkdir(parents=True, exist_ok=True)
    tray_outline, tray_text = palette["surface0"], palette["text"]
    bg, hl = palette['fcitx5_bg'], palette['fcitx5_hl_bg']
    bh, bs, bl = hex_to_hsl(bg)
    border = hsl_to_hex(bh, bs, min(bl + 5, 100))
    hh, hs, hl_val = hex_to_hsl(hl)
    hborder = hsl_to_hex(hh, hs, min(hl_val + 5, 100))
    
    panel_svg = f'<svg xmlns="http://www.w3.org/2000/svg" width="40" height="100"><g><rect width="39" height="99" x=".5" y=".5" fill="{bg}" stroke="{border}" rx="10" ry="10"/></g></svg>'
    highlight_svg = f'<svg xmlns="http://www.w3.org/2000/svg" width="39" height="44"><g><rect width="39" height="44" x="0" y="0" fill="{hl}" stroke="{hborder}" stroke-width="0" rx="8" ry="8"/></g></svg>'
    
    with open(theme_dir / "panel.svg", "w") as f: f.write(panel_svg)
    with open(theme_dir / "highlight.svg", "w") as f: f.write(highlight_svg)
    
    theme = f"""[Metadata]
Name=morandi
Version=0.0.3
Author=morandi-gen
Description=Auto-generated Morandi theme

[InputPanel]
NormalColor={palette['fcitx5_text']}
HighlightColor={palette['fcitx5_hl_text']}
HighlightBackgroundColor={palette['fcitx5_hl_bg']}
HighlightCandidateColor={palette['fcitx5_text']}
EnableBlur=True
FullWidthHighlight=True
PageButtonAlignment=Bottom
[InputPanel/BlurMargin]
Left=0\nRight=0\nTop=0\nBottom=0
[InputPanel/Background]
Image=panel.svg
Color={palette['fcitx5_bg']}
BorderColor={palette['fcitx5_bg']}
BorderWidth=0
[InputPanel/Background/Margin]
Left=6\nRight=6\nTop=6\nBottom=6
[InputPanel/Highlight]
Image=highlight.svg
Color={palette['fcitx5_hl_bg']}
BorderColor={palette['fcitx5_hl_bg']}00
BorderWidth=0
[InputPanel/Highlight/Margin]
Left=4\nRight=4\nTop=3\nBottom=3
[InputPanel/TextMargin]
Left=8\nRight=8\nTop=4\nBottom=4
[Menu]
NormalColor={palette['fcitx5_text']}
HighlightCandidateColor={palette['fcitx5_text']}
Spacing=0
[Menu/Background]
Image=panel.svg
Color={palette['fcitx5_bg']}
BorderColor={palette['fcitx5_bg']}00
BorderWidth=0
[Menu/Background/Margin]
Left=4\nRight=4\nTop=4\nBottom=4
[Menu/Highlight]
Image=highlight.svg
Color={palette['fcitx5_hl_bg']}
BorderColor={palette['fcitx5_hl_bg']}00
BorderWidth=0
[Menu/Highlight/Margin]
Left=2\nRight=2\nTop=1\nBottom=1
[Menu/Separator]
Color={palette['fcitx5_bg_alt']}
BorderColor={palette['fcitx5_bg_alt']}00
BorderWidth=0
"""
    with open(FCITX5_THEME, "w") as f: f.write(theme)
    classicui = Path.home() / ".config/fcitx5/conf/classicui.conf"
    if classicui.exists():
        content = classicui.read_text()
        content = re.sub(r"^Theme=.*", "Theme=morandi", content, flags=re.MULTILINE)
        content = re.sub(r"^DarkTheme=.*", "DarkTheme=morandi", content, flags=re.MULTILINE)
        content = re.sub(r"^UseDarkTheme=.*", "UseDarkTheme=False", content, flags=re.MULTILINE)
        content = re.sub(r"^TrayOutlineColor=.*", f"TrayOutlineColor={tray_outline}", content, flags=re.MULTILINE)
        content = re.sub(r"^TrayTextColor=.*", f"TrayTextColor={tray_text}", content, flags=re.MULTILINE)
        classicui.write_text(content)

def write_fastfetch(palette):
    if not FASTFETCH_CONFIG.exists():
        return
    content = FASTFETCH_CONFIG.read_text()

    content = re.sub(
        r'"color"\s*:\s*\{[^}]*\}',
        f'"color": {{ "keys": "{palette["iris"]}", "title": "{palette["text"]}" }}',
        content,
    )

    if '"disk"' not in content:
        content = content.replace(
            '{ "type": "memory", "key": " \uf0e4 Memory" }',
            '{ "type": "memory", "key": " \uf0e4 Memory" }, { "type": "disk", "key": " \uf0a0 Disk" }',
        )

    FASTFETCH_CONFIG.write_text(content)

ALACRITTY_ORIGINAL_NORMAL = {"black": "#1c1c1c", "red": "#ff6c6b", "green": "#98be65", "yellow": "#ecbe7b", "blue": "#51afef", "magenta": "#c678dd", "cyan": "#46d9ff", "white": "#bbc2cf"}
ALACRITTY_ORIGINAL_BRIGHT = {"black": "#5b6268", "red": "#da8548", "green": "#4db5bd", "yellow": "#ecbe7b", "blue": "#3071db", "magenta": "#a9a1e1", "cyan": "#46d9ff", "white": "#dfdfdf"}

def write_alacritty():
    if not ALACRITTY_TOML.exists(): return
    content = ALACRITTY_TOML.read_text()
    normal_colors = "\n".join(f'{k} = "{morandi(v, 0.45, -5, 0, 40)}"' for k, v in ALACRITTY_ORIGINAL_NORMAL.items())
    bright_colors = "\n".join(f'{k} = "{morandi(v, 0.45, -5, 0, 40)}"' for k, v in ALACRITTY_ORIGINAL_BRIGHT.items())
    content = re.sub(r"\[colors\.normal\]\n(.*?\n)+?(?=\[colors\.bright\])", f"[colors.normal]\n{normal_colors}\n", content, flags=re.MULTILINE)
    content = re.sub(r"\[colors\.bright\]\n(.*?\n)+?(?=\[colors\.cursor\])", f"[colors.bright]\n{bright_colors}\n", content, flags=re.MULTILINE)
    ALACRITTY_TOML.write_text(content)

def hex_to_rgb(hex_color):
    h = hex_color.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def write_kde(colors):
    def rgb_str(c): return f"{c[0]},{c[1]},{c[2]}"
    bg, surface, surface_var = hex_to_rgb(colors["background"]), hex_to_rgb(colors["surface_container"]), hex_to_rgb(colors["surface_variant"])
    primary, primary_cont = hex_to_rgb(colors["primary"]), hex_to_rgb(colors["primary_container"])
    on_surface, on_surface_var, on_primary = hex_to_rgb(colors["on_surface"]), hex_to_rgb(colors["on_surface_variant"]), hex_to_rgb(colors["on_primary"])
    error, window_bg = hex_to_rgb(colors["error"]), hex_to_rgb(colors["surface_container_low"])
    content = f"""[General]\nName=Morandi Dark\nshadeSortColumn=true\n
[Colors:Button]
BackgroundNormal={rgb_str(surface)}\nBackgroundAlternate={rgb_str(surface)}
ForegroundNormal={rgb_str(on_surface)}\nForegroundInactive={rgb_str(on_surface_var)}
ForegroundActive={rgb_str(primary)}\nForegroundLink={rgb_str(primary)}\nForegroundNegative={rgb_str(error)}
DecorationFocus={rgb_str(primary_cont)}\nDecorationHover={rgb_str(primary)}
[Colors:View]
BackgroundNormal={rgb_str(bg)}\nBackgroundAlternate={rgb_str(surface_var)}
ForegroundNormal={rgb_str(on_surface)}\nForegroundInactive={rgb_str(on_surface_var)}
ForegroundActive={rgb_str(primary)}\nForegroundLink={rgb_str(primary)}\nForegroundNegative={rgb_str(error)}
DecorationFocus={rgb_str(primary_cont)}\nDecorationHover={rgb_str(primary)}
[Colors:Window]
BackgroundNormal={rgb_str(window_bg)}\nBackgroundAlternate={rgb_str(window_bg)}
ForegroundNormal={rgb_str(on_surface)}\nForegroundInactive={rgb_str(on_surface_var)}
ForegroundActive={rgb_str(primary)}\nForegroundLink={rgb_str(primary)}\nForegroundNegative={rgb_str(error)}
DecorationFocus={rgb_str(primary_cont)}\nDecorationHover={rgb_str(primary)}
[Colors:Selection]
BackgroundNormal={rgb_str(primary_cont)}\nBackgroundAlternate={rgb_str(primary_cont)}
ForegroundNormal={rgb_str(on_primary)}\nForegroundInactive={rgb_str(on_primary)}\nForegroundActive={rgb_str(on_primary)}
ForegroundLink={rgb_str(on_primary)}\nForegroundNegative={rgb_str(error)}
DecorationFocus={rgb_str(primary_cont)}\nDecorationHover={rgb_str(primary)}
[WM]
activeBackground={rgb_str(surface)}\nactiveForeground={rgb_str(on_surface)}
inactiveBackground={rgb_str(bg)}\ninactiveForeground={rgb_str(on_surface_var)}
activeTitleBtnBg={rgb_str(primary_cont)}\ninactiveTitleBtnBg={rgb_str(surface)}\n"""
    KDE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    KDE_OUTPUT.write_text(content)

def write_blender(palette):
    script_content = f"""import bpy
theme = bpy.context.preferences.themes[0]
theme.name = "Morandi"

def h(hx):
    return [int(hx.lstrip('#')[i:i+2], 16)/255.0 for i in (0, 2, 4)]

def s(o, a, c):
    try:
        setattr(o, a, tuple(c + [1.0]) if len(getattr(o, a)) == 4 else tuple(c))
    except: pass

# Palette shortcuts
bg       = h('{palette["base"]}')
bg_light = h('{palette["surface0"]}')
bg_mid   = h('{palette["surface1"]}')
bg_dark  = h('{palette["mantle"]}')
fg       = h('{palette["text"]}')
fg_dim   = h('{palette["subtext0"]}')
accent   = h('{palette["iris"]}')
accent2  = h('{palette["foam"]}')
green    = h('{palette["pine"]}')
red      = h('{palette["love"]}')
gold     = h('{palette["gold"]}')
peach    = h('{palette["peach"]}')
rose     = h('{palette["rose"]}')
sky      = h('{palette["sky"]}')
iris     = h('{palette["iris"]}')
overlay  = h('{palette["overlay0"]}')

# ── 3D Viewport ──
v3 = theme.view_3d
v3.space.background = bg
v3.space.text = fg
v3.space.header = bg_dark
v3.space.header_text = fg
v3.space.panelcolors.header = bg_light
v3.space.panelcolors.back = bg
s(v3.space.gradients, 'high_gradient', bg)
s(v3.space.gradients, 'low_gradient', bg_dark)
v3.space.grid = overlay
v3.space.wire = fg_dim
v3.space.object_active = accent
v3.space.object_selected = green
v3.space.object_active_wire = accent
v3.space.vertex = fg
v3.space.vertex_active = accent
v3.space.vertex_select = green
v3.space.edge = fg_dim
v3.space.edge_select = green
v3.space.edge_crease = gold
v3.space.edge_bevel = peach
v3.space.edge_seam = red
v3.space.edge_sharp = gold
v3.space.edge_faces = bg_light
v3.space.face = bg_light
v3.space.face_select = green
v3.space.face_back = bg_dark
v3.space.face_dot = accent
v3.space.nurb_sel_uline = green
v3.space.nurb_sel_vline = green
v3.space.nurb_uline = fg_dim
v3.space.nurb_vline = fg_dim
v3.space.skin_root = accent
v3.space.pose_action = rose
v3.space.pose_action_active = peach
v3.space.trimetri_face = bg_light
v3.space.transform = accent
v3.space.frame_current = gold
v3.space.text_keybinding = fg
v3.space.match = green
v3.space.selected_highlight = green
v3.space.selected_object = green

# ── User Interface ──
ui = theme.user_interface
ui.base = bg
ui.text = fg
ui.text_dim = fg_dim
ui.panel = bg_light
ui.panel_title = fg
ui.panel_back = bg_dark
ui.panel_sub = bg_light
ui.button = bg_mid
ui.button_text = fg
ui.button_text_highlight = bg
ui.wcol_regular.inner = bg_light
ui.wcol_regular.inner_sel = accent
ui.wcol_regular.item = fg
ui.wcol_regular.text = fg
ui.wcol_regular.text_sel = bg
ui.wcol_tool.inner = bg_light
ui.wcol_tool.inner_sel = accent
ui.wcol_tool.item = fg
ui.wcol_tool.text = fg
ui.wcol_tool.text_sel = bg
ui.wcol_tool.outline = overlay
ui.wcol_text.inner = bg_light
ui.wcol_text.inner_sel = accent
ui.wcol_text.item = fg
ui.wcol_text.text = fg
ui.wcol_text.text_sel = bg
ui.wcol_option.inner = bg_light
ui.wcol_option.inner_sel = accent
ui.wcol_option.item = fg
ui.wcol_option.text = fg
ui.wcol_option.text_sel = bg
ui.wcol_option.outline = overlay
ui.wcol_menu.inner = bg_light
ui.wcol_menu.inner_sel = accent
ui.wcol_menu.item = fg
ui.wcol_menu.text = fg
ui.wcol_menu.text_sel = bg
ui.wcol_menu.outline = overlay
ui.wcol_pulldown.inner = bg_light
ui.wcol_pulldown.inner_sel = accent
ui.wcol_pulldown.item = fg
ui.wcol_pulldown.text = fg
ui.wcol_pulldown.text_sel = bg
ui.wcol_tab.inner = bg_light
ui.wcol_tab.inner_sel = accent
ui.wcol_tab.item = fg
ui.wcol_tab.text = fg
ui.wcol_tab.text_sel = bg

# ── Header / Toolbar / Properties ──
for sp_name in ['view_3d', 'graph_editor', 'dope_sheet', 'nla_editor',
                 'image_editor', 'uv_editor', 'seqencer', 'seqencer_preview',
                 'text_editor', 'node_editor', 'logic_editor', 'properties',
                 'outliner', 'preferences', 'file_browser', 'info',
                 'console', 'clip_editor', 'spreadsheet']:
    try:
        sp = getattr(theme, sp_name).space
        if hasattr(sp, 'back'): sp.back = bg
        if hasattr(sp, 'text'): sp.text = fg
        if hasattr(sp, 'header'): sp.header = bg_dark
        if hasattr(sp, 'header_text'): sp.header_text = fg
        if hasattr(sp, 'panelcolors'):
            sp.panelcolors.header = bg_light
            sp.panelcolors.back = bg
    except: pass

# ── Graph Editor ──
ge = theme.graph_editor
ge.space.grid = overlay
ge.space.window_sliders = bg_mid
ge.curve_point = accent
ge.curve_selection = green
ge.handle_auto = fg_dim
ge.handle_vector = gold
ge.handle_align = peach
ge.handle_free = red
ge.handle_sel_auto = accent
ge.handle_sel_vector = gold
ge.handle_sel_align = peach
ge.handle_sel_free = red
ge.modifier = sky
ge.modifier_active = iris

# ── Dope Sheet / Action / Shape Key ──
ds = theme.dope_sheet
ds.space.grid = overlay
ds.keyframe_curves = fg_dim
ds.keyframe_border = fg_dim
ds.keyframe_border_selected = green
ds.keyframe_channels_group = fg_dim
ds.keyframe_channels_selected = green
ds.keyframe_inserted = green
ds.keyframe_modified = gold

# ── Node Editor ──
ne = theme.node_editor
ne.space.grid = overlay
ne.space.wire = fg_dim
ne.wire = fg_dim
ne.wire_select = green
ne.node_socket = fg_dim
ne.node_socket_select = green
ne.label = fg
ne.label_selected = bg
ne.backdrop = bg_dark
ne.noodle_curving = 12
ne.grid_level = 1
ne.tree_node = bg_light
ne.tree_node_sel = green
ne.active_node_label = bg
ne.active_node_label_text = accent
ne.node_backdrop = bg_mid
ne.convex_node = bg_light
ne.group_node = bg_mid
ne.frame_node = bg_dark
ne.operator_node = bg_light

# ── Image / UV Editor ──
ie = theme.image_editor
ie.space.background = bg_dark
ie.space.wire = fg_dim
ie.space.pin = accent
ie.wire = fg_dim
ie.face = bg_light
ie.face_select = green
ie.face_dot = accent
ie.vertex = fg
ie.vertex_select = green
ie.stitch = gold
ie.paint = accent
ie.uv_shadow = green
ie.uv_clear = fg_dim

# ── Outliner ──
ol = theme.outliner
ol.space.text = fg
ol.space.back = bg
ol.space.header = bg_dark
ol.space.header_text = fg
ol.active = accent
ol.selected = green
ol.unselected = fg_dim
ol.activated = accent
ol.edited_object = gold

# ── Properties ──
pr = theme.properties
pr.space.text = fg
pr.space.back = bg
pr.space.header = bg_dark
pr.space.header_text = fg
pr.space.panel_back = bg_dark
pr.space.tab_back = bg_light
pr.space.panel_sub = bg_light
pr.space.button = bg_mid
pr.space.button_text = fg
pr.space.wcol_regular.inner = bg_light
pr.space.wcol_regular.inner_sel = accent

# ── Timeline ──
tl = theme.timeline
tl.space.text = fg
tl.space.back = bg_dark
tl.space.header = bg_dark
tl.space.header_text = fg
tl.frame_current = gold
tl.playing = green
tl.preview_range = bg_mid
tl.grid = overlay

# ── Console / Info / Text Editor ──
console_theme = theme.console
console_theme.space.text = fg
console_theme.space.back = bg
console_theme.space.header = bg_dark
console_theme.space.header_text = fg
console_theme.output = fg
console_theme.input = accent
console_theme.info = green
console_theme.error = red
console_theme.cursor = gold
console_theme.selection = bg_mid

info_theme = theme.info
info_theme.space.text = fg
info_theme.space.back = bg
info_theme.space.header = bg_dark
info_theme.space.header_text = fg
info_theme.selected = green
info_theme.selected_text = fg
info_theme.info = fg_dim
info_theme.warning = gold
info_theme.error = red

text_theme = theme.text_editor
text_theme.space.text = fg
text_theme.space.back = bg
text_theme.space.header = bg_dark
text_theme.space.header_text = fg
text_theme.space.line_numbers_background = bg_dark
text_theme.space.line_numbers = fg_dim
text_theme.space.syntax_builtin = iris
text_theme.space.syntax_number = peach
text_theme.space.syntax_string = green
text_theme.space.syntax_special = gold
text_theme.space.syntax_comment = fg_dim
text_theme.space.syntax_identifier = fg
text_theme.space.syntax_symbol = fg_dim
text_theme.space.syntax_predefined = rose
text_theme.space.cursor = gold
text_theme.space.selection_background = bg_mid

# ── Preferences ──
pref = theme.preferences
pref.space.text = fg
pref.space.back = bg
pref.space.header = bg_dark
pref.space.header_text = fg

# ── File Browser ──
fb = theme.file_browser
fb.space.text = fg
fb.space.back = bg
fb.space.header = bg_dark
fb.space.header_text = fg
fb.space.panel_back = bg_dark

# ── Sequencer ──
sq = theme.sequencer
sq.space.text = fg
sq.space.back = bg_dark
sq.space.header = bg_dark
sq.space.header_text = fg
sq.space.grid = overlay
sq.strip = bg_light
sq.strip_select = green
sq.strip_active = accent
sq.strip_duplicate = gold
sq.strip_retime = peach
sq.strip_media = sky

# ── Clip Editor ──
ce = theme.clip_editor
ce.space.text = fg
ce.space.back = bg_dark
ce.space.header = bg_dark
ce.space.header_text = fg

# ── Viewport Navigation / Overlay ──
v3.space.text = fg
v3.space.text_cursor = gold
v3.space.view_overlay = fg_dim
v3.space.view_overlay_text = fg
v3.space.bone_solid = bg_mid
v3.space.bone_pose = accent
v3.space.bone_pose_active = gold
v3.space.bone_outline = fg_dim

# ── Theme status bar / region ──
ui.status = bg_dark
ui.status_text = fg_dim

bpy.ops.wm.save_userpref()
"""
    import tempfile
    with tempfile.NamedTemporaryFile('w', suffix='.py', delete=False) as f:
        f.write(script_content)
        temp_path = f.name
    subprocess.run(["blender", "-b", "-P", temp_path], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    os.remove(temp_path)

def write_godot(palette):
    godot_settings = list(Path.home().glob(".config/godot/editor_settings-*.tres"))
    if not godot_settings: return
    
    def hex_to_color(hex_str):
        hex_str = hex_str.lstrip('#')
        r, g, b = (int(hex_str[i:i+2], 16)/255.0 for i in (0, 2, 4))
        return f"Color({r:.3f}, {g:.3f}, {b:.3f}, 1)"
        
    base_color = hex_to_color(palette["base"])
    accent_color = hex_to_color(palette["iris"])
    
    for path in godot_settings:
        content = path.read_text()
        content = re.sub(r'interface/theme/base_color\s*=\s*Color\([^)]+\)', f'interface/theme/base_color = {base_color}', content)
        content = re.sub(r'interface/theme/accent_color\s*=\s*Color\([^)]+\)', f'interface/theme/accent_color = {accent_color}', content)
        content = re.sub(r'interface/theme/color_preset\s*=\s*".*"', 'interface/theme/color_preset = "Custom"', content)
        path.write_text(content)

def write_obs(palette):
    obs_theme_dir = Path.home() / ".config/obs-studio/themes"
    obs_theme_dir.mkdir(parents=True, exist_ok=True)
    
    def rgb_str(hex_c):
        r, g, b = hex_to_rgb(hex_c)
        return f"rgb({r},{g},{b})"
        
    def darken(hex_c, amount=10):
        return morandi(hex_c, 0, -amount, 0, 100)

    obs_iris = darken(palette['iris'], 12)
    obs_foam = darken(palette['foam'], 12)
    obs_sky = darken(palette['sky'], 12)

    content = f"""@OBSThemeMeta {{
    name: 'Morandi';
    id: 'com.obsproject.Yami.Morandi';
    extends: 'com.obsproject.Yami';
    author: 'morandi-gen';
    dark: 'true';
}}

@OBSThemeVars {{
    --primary: {rgb_str(obs_iris)};
    --primary_light: {rgb_str(obs_foam)};
    --primary_lighter: {rgb_str(obs_sky)};
    --primary_dark: {rgb_str(palette['pine'])};
    --primary_darker: {rgb_str(palette['base'])};

    --blue1: {rgb_str(obs_sky)};
    --blue2: {rgb_str(obs_foam)};
    --blue3: {rgb_str(obs_iris)};
    --blue4: {rgb_str(palette['pine'])};
    --blue5: {rgb_str(palette['surface1'])};
    --blue6: {rgb_str(palette['surface0'])};

    --bg_base: {rgb_str(palette['mantle'])};
    --bg_window: {rgb_str(palette['base'])};
    --bg_preview: {rgb_str(palette['mantle'])};

    --border_color: {rgb_str(palette['surface1'])};

    --input_bg: {rgb_str(palette['surface0'])};
    --input_bg_hover: {rgb_str(palette['surface1'])};
    --input_bg_focus: {rgb_str(palette['surface1'])};

    --list_item_bg_selected: {rgb_str(palette['surface0'])};
    --list_item_bg_hover: {rgb_str(palette['surface1'])};

    --input_border: {rgb_str(palette['surface2'])};
    --input_border_hover: {rgb_str(obs_iris)};
    --input_border_focus: {rgb_str(obs_iris)};

    --button_bg: {rgb_str(palette['surface0'])};
    --button_bg_hover: {rgb_str(palette['surface1'])};
    --button_bg_down: {rgb_str(palette['surface2'])};
    --button_bg_disabled: {rgb_str(palette['mantle'])};

    --button_bg_red: {rgb_str(palette['love'])};
    --button_bg_red_hover: {rgb_str(palette['rose'])};
    --button_bg_red_down: {rgb_str(palette['love'])};

    --button_border: {rgb_str(palette['surface2'])};
    --button_border_hover: {rgb_str(obs_iris)};
    --button_border_focus: {rgb_str(obs_iris)};

    --tab_bg: {rgb_str(palette['surface0'])};
    --tab_bg_hover: {rgb_str(palette['surface1'])};
    --tab_bg_down: {rgb_str(palette['surface2'])};
    --tab_bg_disabled: {rgb_str(palette['mantle'])};

    --tab_border: {rgb_str(palette['surface0'])};
    --tab_border_hover: {rgb_str(palette['surface2'])};
    --tab_border_focus: {rgb_str(palette['surface2'])};
    --tab_border_selected: {rgb_str(obs_iris)};

    --scrollbar_handle: {rgb_str(palette['surface1'])};
    --scrollbar_hover: {rgb_str(palette['surface2'])};
    --scrollbar_down: {rgb_str(palette['surface0'])};
    --scrollbar_border: {rgb_str(palette['surface1'])};

    --toolbutton_bg: {rgb_str(palette['surface0'])};
    --toolbutton_bg_hover: {rgb_str(palette['surface1'])};
    --toolbutton_bg_down: {rgb_str(palette['surface2'])};
    --toolbutton_bg_disabled: {rgb_str(palette['mantle'])};
}}
"""
    (obs_theme_dir / "Yami_Morandi.ovt").write_text(content)
    
    obs_config = Path.home() / ".config/obs-studio/global.ini"
    if obs_config.exists():
        conf = obs_config.read_text()
        conf = re.sub(r"^CurrentTheme3=.*", "CurrentTheme3=Yami_Morandi", conf, flags=re.MULTILINE)
        obs_config.write_text(conf)

def write_clash_verge(palette):
    config_path = Path.home() / ".local/share/io.github.clash-verge-rev.clash-verge-rev/verge.yaml"
    if not config_path.exists():
        return

    content = config_path.read_text()

    css = f""":root {{
  --joy-palette-background-body: {palette['base']} !important;
  --joy-palette-background-surface: {palette['surface0']} !important;
  --joy-palette-background-level1: {palette['surface1']} !important;
  --joy-palette-background-level2: {palette['surface2']} !important;
  --joy-palette-background-level3: {palette['overlay0']} !important;
  --mui-palette-background-default: {palette['base']} !important;
  --mui-palette-background-paper: {palette['surface0']} !important;
  --bg-base: {palette['base']} !important;
  --bg-surface: {palette['surface0']} !important;
  --mui-palette-primary-contrastText: #ffffff !important;
  --joy-palette-primary-solidColor: #ffffff !important;
}}
body, #root, main, .MuiDrawer-paper, .MuiAppBar-root, .layout-content, .page, .page-content {{
  background-color: {palette['base']} !important;
  background-image: none !important;
  color: {palette['text']} !important;
}}
.MuiPaper-root, .MuiCard-root, .MuiDialog-paper, .MuiPopover-paper {{
  background-color: {palette['surface0']} !important;
  background-image: none !important;
  border-radius: 12px !important;
  border: 1px solid {palette['surface1']} !important;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15) !important;
}}
.Mui-selected, .Mui-selected *, .MuiButton-containedPrimary, .MuiButton-containedPrimary *, .clash-active {{
  color: #ffffff !important;
}}
* {{
  transition: background-color 0.4s cubic-bezier(0.4, 0, 0.2, 1), 
              border-color 0.4s cubic-bezier(0.4, 0, 0.2, 1),
              color 0.4s cubic-bezier(0.4, 0, 0.2, 1),
              box-shadow 0.4s cubic-bezier(0.4, 0, 0.2, 1),
              transform 0.3s cubic-bezier(0.4, 0, 0.2, 1) !important;
}}
.MuiButtonBase-root:hover, .MuiMenuItem-root:hover, .clash-hover-effect:hover {{
  transform: translateY(-2px) !important;
  box-shadow: 0 6px 16px rgba(0,0,0,0.2) !important;
}}
.MuiButtonBase-root:active, .MuiMenuItem-root:active, .clash-hover-effect:active {{
  transform: translateY(1px) !important;
  box-shadow: none !important;
}}"""

    css_indented = "\n    ".join(css.split("\n"))
    
    theme_setting = f"theme_setting:\n  primary_color: '{palette['iris']}'\n  secondary_color: '{palette['foam']}'\n  info_color: '{palette['sky']}'\n  error_color: '{palette['love']}'\n  warning_color: '{palette['gold']}'\n  success_color: '{palette['pine']}'\n  css_injection: |\n    {css_indented}"
    
    if "theme_setting: null" in content:
        content = re.sub(r"^theme_setting:\s*null", theme_setting, content, flags=re.MULTILINE)
    elif re.search(r"^theme_setting:", content, flags=re.MULTILINE):
        content = re.sub(r"^theme_setting:.*(\n\s+.*)*", theme_setting, content, flags=re.MULTILINE)
    else:
        content += "\n" + theme_setting + "\n"
        
    content = re.sub(r"^css_injection:.*(\n\s+.*)*", "", content, flags=re.MULTILINE).strip() + "\n"
        
    config_path.write_text(content)




def apply_system_changes(wallpaper_path=None):
    def run_ignore_missing(*args, **kwargs):
        try:
            subprocess.run(*args, **kwargs)
        except FileNotFoundError:
            pass

    env = os.environ.copy()
    env["DISPLAY"] = ":0"
    env["XDG_RUNTIME_DIR"] = f"/run/user/{os.getuid()}"
    run_ignore_missing(["dbus-send", "--session", "--dest=org.kde.plasmashell", "--type=method_call", "/PlasmaShell", "org.kde.PlasmaShell.evaluateScript", "string: var allDesktops = desktops(); for (var i=0; i<allDesktops.length; i++) { allDesktops[i].wallpaperPlugin = '' }"], env=env, stderr=subprocess.DEVNULL)
    run_ignore_missing(["qdbus", "org.kde.KWin", "/KWin", "reconfigure"], env=env, stderr=subprocess.DEVNULL)
    run_ignore_missing(["niri", "msg", "action", "load-config-file"], stderr=subprocess.DEVNULL)
    run_ignore_missing(["mmsg", "reload_config"], stderr=subprocess.DEVNULL)
    run_ignore_missing(["pkill", "-USR2", "cava"], stderr=subprocess.DEVNULL)
    
    if wallpaper_path and Path(wallpaper_path).exists():
        efi_dir = "/boot/efi"
        subprocess.run(["sudo", "magick", wallpaper_path, "-blur", "0x12", "-resize", "1920x1080!", "-quality", "95", f"{efi_dir}/limine_bg.png"], stderr=subprocess.DEVNULL)
        
    try:
        pid = subprocess.check_output(["pgrep", "-x", "fcitx5"]).decode().strip()
        if pid:
            subprocess.run(["kill", pid])
            subprocess.run(["sleep", "0.3"])
    except subprocess.CalledProcessError:
        pass
    subprocess.Popen(["fcitx5"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, start_new_session=True)

def write_flclash(palette):
    config_path = Path.home() / ".local/share/com.follow.clash/shared_preferences.json"
    if not config_path.exists():
        return
        
    try:
        with open(config_path, "r") as f:
            data = json.load(f)
            
        if "flutter.config" in data:
            flutter_config = json.loads(data["flutter.config"])
            
            hex_color = palette['iris'].lstrip('#')
            if len(hex_color) == 6:
                argb_int = int("ff" + hex_color, 16)
            else:
                argb_int = int(hex_color, 16)
                
            if "themeProps" not in flutter_config:
                flutter_config["themeProps"] = {}
                
            flutter_config["themeProps"]["primaryColor"] = argb_int
            flutter_config["themeProps"]["pureBlack"] = False
            flutter_config["themeProps"]["themeMode"] = "dark"
            
            data["flutter.config"] = json.dumps(flutter_config, separators=(',', ':'))
            
            with open(config_path, "w") as f:
                json.dump(data, f, separators=(',', ':'))
    except Exception as e:
        print(f"Failed to write flclash theme: {e}")

def write_cava(palette):
    cava_dir = Path.home() / ".config/cava"
    theme_dir = cava_dir / "themes"
    theme_dir.mkdir(parents=True, exist_ok=True)
    theme_path = theme_dir / "morandi"
    content = f"""; Auto-generated by morandi-gen.py — do not edit manually
[color]
background = 'default'
foreground = '{palette['iris']}'

gradient = 1
gradient_color_1 = '{palette['sky']}'
gradient_color_2 = '{palette['foam']}'
gradient_color_3 = '{palette['pine']}'
gradient_color_4 = '{palette['iris']}'
gradient_color_5 = '{palette['gold']}'
gradient_color_6 = '{palette['peach']}'
gradient_color_7 = '{palette['rose']}'
gradient_color_8 = '{palette['love']}'
"""
    theme_path.write_text(content)


def write_libswell(palette):
    swell_conf = Path.home() / ".config/REAPER/libSwell-user.colortheme"
    if not swell_conf.exists(): return
    content = swell_conf.read_text()
    
    bg = palette["base"]
    bg_alt = palette["mantle"]
    bg_dark = morandi(palette["base"], 0, -3)
    text = palette["text"]
    text_dim = palette["subtext0"]
    accent = palette["iris"]
    
    replacements = {
        "#333333": bg, "#2e2e2e": bg_alt, "#282828": bg_alt, "#2a2a2a": bg_alt,
        "#303030": bg, "#2f2f2f": bg_alt, "#292929": bg_alt, "#242424": bg_dark,
        "#202020": bg_dark, "#353535": bg_dark, "#2c2c2c": bg_dark,
        "#d1a660": accent, "#d1d1d1": text, "#c3c3c3": text_dim,
        "#9a9a9a": text_dim, "#7a7a7a": text_dim, "#777777": text_dim,
        "#676767": text_dim, "#585858": text_dim, "#050505": bg_dark,
        "#1a1a1a": bg_alt, "#e6e6e6": text, "#1A1A1A": bg_alt, "#E6E6E6": text
    }
    
    content = re.sub(r"#[0-9a-fA-F]{6}", lambda m: replacements.get(m.group(0), m.group(0).lower()), content)
    # also try lower casing for the map
    content = re.sub(r"#[0-9a-fA-F]{6}", lambda m: replacements.get(m.group(0).lower(), m.group(0)), content)
    swell_conf.write_text(content)

def write_zed(palette):
    zed_theme_dir = Path.home() / ".config/zed/themes"
    zed_theme_dir.mkdir(parents=True, exist_ok=True)
    
    theme = {
        "$schema": "https://zed.dev/schema/themes/v0.1.0.json",
        "name": "Morandi",
        "author": "morandi-gen",
        "themes": [
            {
                "name": "Morandi",
                "appearance": "dark",
                "style": {
                    "border": palette["surface2"],
                    "border.variant": palette["surface1"],
                    "border.focused": palette["iris"],
                    "border.selected": palette["iris"],
                    "border.transparent": "#00000000",
                    "border.disabled": palette["surface1"],
                    "elevated_surface.background": palette["surface0"],
                    "surface.background": palette["base"],
                    "background": palette["base"],
                    "element.background": palette["base"],
                    "element.hover": palette["surface0"],
                    "element.active": palette["surface1"],
                    "element.selected": palette["surface1"],
                    "element.disabled": palette["base"],
                    "drop_target.background": palette["surface1"],
                    "ghost_element.background": "#00000000",
                    "ghost_element.hover": palette["surface0"],
                    "ghost_element.active": palette["surface1"],
                    "ghost_element.selected": palette["surface1"],
                    "ghost_element.disabled": "#00000000",
                    "text": palette["text"],
                    "text.muted": palette["subtext0"],
                    "text.placeholder": palette["subtext1"],
                    "text.disabled": palette["subtext0"],
                    "text.accent": palette["iris"],
                    "icon": palette["text"],
                    "icon.muted": palette["subtext0"],
                    "icon.disabled": palette["subtext0"],
                    "icon.placeholder": palette["subtext1"],
                    "icon.accent": palette["iris"],
                    "status_bar.background": palette["mantle"],
                    "title_bar.background": palette["mantle"],
                    "toolbar.background": palette["mantle"],
                    "tab_bar.background": palette["mantle"],
                    "tab.inactive_background": palette["mantle"],
                    "tab.active_background": palette["base"],
                    "panel.background": palette["mantle"],
                    "panel.focused_border": palette["iris"],
                    "editor.foreground": palette["text"],
                    "editor.background": palette["base"],
                    "editor.gutter.background": palette["base"],
                    "editor.line_number": palette["overlay0"],
                    "editor.active_line_number": palette["text"],
                    "editor.active_line.background": palette["surface0"],
                    "editor.highlighted_line.background": palette["surface0"],
                    "editor.invisible": palette["surface1"],
                    "editor.wrap_guide": palette["surface1"],
                    "editor.active_wrap_guide": palette["surface2"],
                    "search.match_background": palette["surface2"],
                    "terminal.background": palette["base"],
                    "terminal.foreground": palette["text"],
                    "terminal.ansi.black": palette["surface1"],
                    "terminal.ansi.red": palette["love"],
                    "terminal.ansi.green": blend(palette["pine"], palette["surface1"], 0.4),
                    "terminal.ansi.yellow": palette["gold"],
                    "terminal.ansi.blue": blend(palette["iris"], palette["surface1"], 0.4),
                    "terminal.ansi.magenta": palette["rose"],
                    "terminal.ansi.cyan": blend(palette["sky"], palette["surface1"], 0.4),
                    "terminal.ansi.white": palette["text"],
                    "terminal.ansi.bright_black": palette["surface2"],
                    "terminal.ansi.bright_red": palette["love"],
                    "terminal.ansi.bright_green": blend(palette["pine"], palette["surface1"], 0.4),
                    "terminal.ansi.bright_yellow": palette["gold"],
                    "terminal.ansi.bright_blue": blend(palette["iris"], palette["surface1"], 0.4),
                    "terminal.ansi.bright_magenta": palette["rose"],
                    "terminal.ansi.bright_cyan": blend(palette["sky"], palette["surface1"], 0.4),
                    "terminal.ansi.bright_white": palette["text"],
                    "players": [
                        {
                            "cursor": palette["pine"],
                            "background": palette["pine"],
                            "selection": palette["surface2"]
                        }
                    ],
                    "created": palette["pine"] + "50",
                    "modified": palette["iris"] + "50",
                    "deleted": palette["love"] + "50",
                    "conflict": palette["peach"] + "50",
                    "ignored": palette["subtext0"],
                    "hint": palette["subtext0"],
                    "info": palette["foam"],
                    "predictive": palette["subtext0"],
                    "scrollbar_thumb.background": palette["surface2"] + "80",
                    "scrollbar.thumb.background": palette["surface2"] + "80",
                    "scrollbar.thumb.hover_background": palette["surface2"] + "c0",
                    "scrollbar.track.background": "#00000000",
                    "scrollbar.track.border": "#00000000",
                    "syntax": {
                        "keyword": {"color": palette["rose"]},
                        "function": {"color": palette["iris"]},
                        "string": {"color": palette["pine"]},
                        "type": {"color": palette["gold"]},
                        "number": {"color": palette["peach"]},
                        "constant": {"color": palette["peach"]},
                        "property": {"color": palette["text"]},
                        "variable": {"color": palette["text"]},
                        "comment": {"color": palette["subtext0"], "font_style": "italic"},
                        "punctuation": {"color": palette["subtext0"]},
                        "operator": {"color": palette["subtext0"]},
                        "boolean": {"color": palette["peach"]},
                        "label": {"color": palette["pine"]},
                        "predictive": {"color": palette["subtext0"], "font_style": "italic"}
                    }
                }
            }
        ]
    }
    
    (zed_theme_dir / "morandi.json").write_text(json.dumps(theme, indent=2))


def write_vscode(palette):
    vscode_ext_dir = Path.home() / ".vscode/extensions/morandi-theme-0.0.1/themes"
    vscode_user_dir = Path.home() / ".config/Code/User/themes"
    vscode_ext_dir.mkdir(parents=True, exist_ok=True)
    vscode_user_dir.mkdir(parents=True, exist_ok=True)

    theme = {
        "name": "Morandi",
        "type": "dark",
        "colors": {
            "editor.background": palette["base"],
            "editor.foreground": palette["text"],
            "editorLineNumber.foreground": palette["overlay0"],
            "editorLineNumber.activeForeground": palette["text"],
            "editor.lineHighlightBackground": palette["surface0"],
            "editor.selectionBackground": palette["surface2"],
            "editor.inactiveSelectionBackground": palette["surface1"],
            "editorCursor.foreground": palette["pine"],
            "editorWhitespace.foreground": palette["surface1"],
            "editorIndentGuide.background": palette["surface1"],
            "editorIndentGuide.activeBackground": palette["surface2"],
            "editor.findMatchBackground": palette["surface2"],
            "editor.findMatchHighlightBackground": palette["surface2"] + "80",
            "editorBracketMatch.background": palette["surface2"] + "80",
            "editorBracketMatch.border": palette["iris"],
            "editorGutter.background": palette["base"],
            "editorWidget.background": palette["surface0"],
            "editorWidget.border": palette["surface2"],
            "editorSuggestWidget.background": palette["surface0"],
            "editorSuggestWidget.border": palette["surface2"],
            "editorSuggestWidget.selectedBackground": palette["surface1"],
            "editorHoverWidget.background": palette["surface0"],
            "editorHoverWidget.border": palette["surface2"],
            "minimap.background": palette["base"] + "cc",
            "scrollbarSlider.background": palette["surface2"] + "80",
            "scrollbarSlider.hoverBackground": palette["surface2"] + "c0",
            "scrollbarSlider.activeBackground": palette["surface2"],
            "sideBar.background": palette["mantle"],
            "sideBar.foreground": palette["text"],
            "sideBar.border": palette["surface1"],
            "sideBarTitle.foreground": palette["text"],
            "sideBarSectionHeader.background": palette["mantle"],
            "sideBarSectionHeader.foreground": palette["subtext0"],
            "statusBar.background": palette["mantle"],
            "statusBar.foreground": palette["subtext0"],
            "statusBar.border": palette["surface1"],
            "titleBar.activeBackground": palette["mantle"],
            "titleBar.activeForeground": palette["subtext0"],
            "titleBar.inactiveBackground": palette["mantle"],
            "titleBar.border": palette["surface1"],
            "tab.activeBackground": palette["base"],
            "tab.activeForeground": palette["text"],
            "tab.inactiveBackground": palette["mantle"],
            "tab.inactiveForeground": palette["subtext0"],
            "tab.activeBorderTop": palette["iris"],
            "tab.border": palette["mantle"],
            "editorGroupHeader.tabsBackground": palette["mantle"],
            "editorGroupHeader.tabsBorder": palette["surface1"],
            "panel.background": palette["mantle"],
            "panel.border": palette["surface1"],
            "panelTitle.activeBorder": palette["iris"],
            "panelTitle.activeForeground": palette["text"],
            "panelTitle.inactiveForeground": palette["subtext0"],
            "terminal.background": palette["base"],
            "terminal.foreground": palette["text"],
            "terminal.ansiBlack": palette["surface1"],
            "terminal.ansiRed": palette["love"],
            "terminal.ansiGreen": palette["pine"],
            "terminal.ansiYellow": palette["gold"],
            "terminal.ansiBlue": palette["iris"],
            "terminal.ansiMagenta": palette["rose"],
            "terminal.ansiCyan": palette["sky"],
            "terminal.ansiWhite": palette["text"],
            "terminal.ansiBrightBlack": palette["surface2"],
            "terminal.ansiBrightRed": palette["love"],
            "terminal.ansiBrightGreen": palette["pine"],
            "terminal.ansiBrightYellow": palette["gold"],
            "terminal.ansiBrightBlue": palette["iris"],
            "terminal.ansiBrightMagenta": palette["rose"],
            "terminal.ansiBrightCyan": palette["sky"],
            "terminal.ansiBrightWhite": palette["text"],
            "input.background": palette["surface0"],
            "input.border": palette["surface2"],
            "input.foreground": palette["text"],
            "input.placeholderForeground": palette["subtext0"],
            "inputOption.activeBorder": palette["iris"],
            "dropdown.background": palette["surface0"],
            "dropdown.border": palette["surface2"],
            "dropdown.foreground": palette["text"],
            "button.background": palette["iris"],
            "button.foreground": palette["base"],
            "button.hoverBackground": palette["iris"] + "cc",
            "list.activeSelectionBackground": palette["surface1"],
            "list.activeSelectionForeground": palette["text"],
            "list.hoverBackground": palette["surface0"],
            "list.focusBackground": palette["surface1"],
            "list.highlightForeground": palette["iris"],
            "gitDecoration.modifiedResourceForeground": palette["iris"],
            "gitDecoration.deletedResourceForeground": palette["love"],
            "gitDecoration.untrackedResourceForeground": blend(palette["pine"], palette["surface1"], 0.4),
            "gitDecoration.conflictingResourceForeground": palette["peach"],
            "gitDecoration.ignoredResourceForeground": palette["subtext0"],
            "diffEditor.insertedTextBackground": palette["pine"] + "20",
            "diffEditor.removedTextBackground": palette["love"] + "20",
        },
        "tokenColors": [
            {
                "scope": ["comment", "punctuation.definition.comment"],
                "settings": {
                    "foreground": palette["subtext0"],
                    "fontStyle": "italic"
                }
            },
            {
                "scope": [
                    "keyword",
                    "keyword.control",
                    "keyword.operator.new",
                    "keyword.operator.expression",
                    "storage",
                    "storage.type",
                    "storage.modifier"
                ],
                "settings": {
                    "foreground": palette["rose"]
                }
            },
            {
                "scope": [
                    "entity.name.function",
                    "support.function",
                    "meta.function-call"
                ],
                "settings": {
                    "foreground": palette["iris"]
                }
            },
            {
                "scope": [
                    "string",
                    "string.quoted",
                    "string.template"
                ],
                "settings": {
                    "foreground": palette["pine"]
                }
            },
            {
                "scope": [
                    "entity.name.type",
                    "entity.other.inherited-class",
                    "support.type",
                    "support.class"
                ],
                "settings": {
                    "foreground": palette["gold"]
                }
            },
            {
                "scope": [
                    "constant.numeric",
                    "constant.language"
                ],
                "settings": {
                    "foreground": palette["peach"]
                }
            },
            {
                "scope": ["variable.other", "variable.language"],
                "settings": {
                    "foreground": palette["text"]
                }
            },
            {
                "scope": ["variable.parameter", "variable.other.readwrite"],
                "settings": {
                    "foreground": palette["text"]
                }
            },
            {
                "scope": ["entity.name.tag"],
                "settings": {
                    "foreground": palette["rose"]
                }
            },
            {
                "scope": ["entity.other.attribute-name"],
                "settings": {
                    "foreground": palette["gold"]
                }
            },
            {
                "scope": ["punctuation"],
                "settings": {
                    "foreground": palette["subtext0"]
                }
            },
            {
                "scope": ["keyword.operator"],
                "settings": {
                    "foreground": palette["subtext0"]
                }
            },
            {
                "scope": ["support.constant"],
                "settings": {
                    "foreground": palette["peach"]
                }
            },
            {
                "scope": ["entity.name.class", "entity.name.type.class"],
                "settings": {
                    "foreground": palette["gold"]
                }
            },
            {
                "scope": ["entity.name.namespace"],
                "settings": {
                    "foreground": palette["gold"]
                }
            },
            {
                "scope": ["markup.heading", "entity.name.section"],
                "settings": {
                    "foreground": palette["iris"],
                    "fontStyle": "bold"
                }
            },
            {
                "scope": ["markup.italic"],
                "settings": {
                    "fontStyle": "italic"
                }
            },
            {
                "scope": ["markup.bold"],
                "settings": {
                    "fontStyle": "bold"
                }
            },
            {
                "scope": ["markup.deleted"],
                "settings": {
                    "foreground": palette["love"]
                }
            },
            {
                "scope": ["markup.inserted"],
                "settings": {
                    "foreground": palette["pine"]
                }
            },
            {
                "scope": ["markup.changed"],
                "settings": {
                    "foreground": palette["gold"]
                }
            },
        ]
    }

    theme_json = json.dumps(theme, indent=4)
    ext_path = vscode_ext_dir / "morandi.json"
    ext_path.write_text(theme_json)
    user_path = vscode_user_dir / "morandi.json"
    user_path.write_text(theme_json)
    print(f"VSCode Morandi theme written to {ext_path} and {user_path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--wallpaper", help="Path to current wallpaper for limine sync")
    args = parser.parse_args()

    if not NOCTALIA_COLORS.exists():
        print(f"Error: {NOCTALIA_COLORS} not found")
        sys.exit(1)

    with open(NOCTALIA_COLORS) as f:
        colors = json.load(f)

    palette = generate_palette(colors)
    write_niri(palette)
    write_mango(palette)
    write_starship(palette)
    write_fcitx5(palette)
    write_fastfetch(palette)
    write_alacritty()
    write_kde(colors)
    write_obs(palette)
    write_clash_verge(palette)
    write_cava(palette)
    write_flclash(palette)
    write_libswell(palette)
    write_zed(palette)
    write_vscode(palette)

    apply_system_changes(args.wallpaper)
    
    try:
        write_blender(palette)
    except Exception as e:
        print(f"Failed to write blender theme: {e}")
        
    try:
        write_godot(palette)
    except Exception as e:
        print(f"Failed to write godot theme: {e}")
        

    try:
        write_obs(palette)
    except Exception as e:
        print(f"Failed to write obs theme: {e}")

    apply_system_changes(args.wallpaper)
    print("Morandi theme generated and system changes applied successfully.")

if __name__ == "__main__":
    main()
