# ────────────── Autostart ──────────────
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = fcitx5 -d
exec-once = noctalia
exec-once = clipse -listen
exec-once = /home/lanrhyme/Projects/slugcatpet/start.sh
