# ────────────── Hyprland Plugins ──────────────
plugin = /var/cache/hyprpm/lanrhyme/hyprexpo/hyprexpo.so

plugin {
    hyprexpo {
        columns = 3
        gaps_in = 8
        gaps_out = 16
        bg_col = $shadowColor
        workspace_method = center current
        tile_rounding = 10
        animate_entry = true
    }
}
