# ────────────── Window Rules ──────────────
windowrule = float on, match:class ^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = float on, match:class ^(pavucontrol)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = float on, match:class ^(clipse)$
windowrule = size 620 650, match:class ^(clipse)$

windowrule = float on, match:title ^(slugcatpet)$
windowrule = pin on, match:title ^(slugcatpet)$
windowrule = border_size 0, match:title ^(slugcatpet)$
windowrule = no_shadow on, match:title ^(slugcatpet)$

windowrule = border_size 0, match:class ^(kando)$
windowrule = no_blur on, match:class ^(kando)$
windowrule = no_shadow on, match:class ^(kando)$
windowrule = float on, match:class ^(kando)$
windowrule = pin on, match:class ^(kando)$

windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$
