# ────────────── Window Rules & Layer Rules ──────────────
# Noctalia Bar & Panel Blur
layerrule = blur, noctalia
layerrule = ignorealpha 0.5, noctalia
layerrule = blur, gtk-layer-shell
layerrule = ignorezero, gtk-layer-shell

# Floating utilities
windowrulev2 = float, class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:^(nm-connection-editor)$
windowrulev2 = float, class:^(clipse)$
windowrulev2 = size 620 650, class:^(clipse)$

# Slugcatpet
windowrulev2 = float, title:^(slugcatpet)$
windowrulev2 = pin, title:^(slugcatpet)$
windowrulev2 = noborder, title:^(slugcatpet)$
windowrulev2 = noshadow, title:^(slugcatpet)$

# Kando Menu
windowrulev2 = noborder, class:^(kando)$
windowrulev2 = noblur, class:^(kando)$
windowrulev2 = noshadow, class:^(kando)$
windowrulev2 = float, class:^(kando)$
windowrulev2 = pin, class:^(kando)$

# Picture-in-Picture
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
